FROM jerry2458/spark_only:1.0

ARG spark_uid=185

RUN set -ex && \
    sed -i 's/http://deb.(.)/https://deb.\1/g' /etc/apt/sources.list && \
    apt-get update && \
    ln -s /lib /lib64 && \
    mkdir -p /spark/work-dir && \
    rm /bin/sh && \
    ln -sv /bin/bash /bin/sh && \
    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
    chgrp root /etc/passwd && chmod ug+rw /etc/passwd && \
    apt-get update && \
    apt install -y python3 python3-pip && \
    pip3 install --upgrade pip setuptools && \
    rm -r /root/.cache && rm -rf /var/cache/apt/

COPY entrypoint.sh /
COPY decom.sh /

WORKDIR /spark/work-dir
RUN chmod g+w /spark/work-dir
RUN chmod a+x /decom.sh

ENTRYPOINT [ "/entrypoint.sh" ]
