apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services" ]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

---
apiVersion : v1
kind: ServiceAccount
metadata: 
  labels:
    k8s-app: spark
  name: spark
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default
